### PR TITLE
Nav 66 add logic for multiple day connections

### PR DESCRIPTION
**Pull request by clukas1**
Final pull request for multi day raptor. I think the performance has been impacted by this addition, however I want to address this in a separate issue (I've got some ideas). I don't see a reason to change the external interface or or the tests when trying to improve the performance.

### CODE REVIEW

**Comment by munterfi** [comment]
Thanks @clukas1, very nice work! Really cool that we only need one raptor instance now.

Some early remarks on the usage of the service, before I start reviewing the code changes itself.

- Maybe we should reduce the log level to debug and only output the first log statement in INFO (also better for performance):
  ```txt
  2024-07-09T11:56:33.573+02:00  INFO 14132 --- [nio-8080-exec-3] ch.naviqore.raptor.router.RaptorRouter   : Routing earliest arrival from [Parent8503059, 8503059] to [8516161:0:2, 8516161:0:3, 8516161:0:5, 8516161:0:6, 8516161:0:7, Parent8516161, 8516161:0:1] departing at [2008-07-09T01:05, 2008-07-09T01:05]
  2024-07-09T11:56:33.573+02:00  WARN 14132 --- [nio-8080-exec-3] ch.naviqore.raptor.router.RaptorRouter   : Stop ID Parent8503059 not found in lookup removing from query.
  2024-07-09T11:56:33.573+02:00  WARN 14132 --- [nio-8080-exec-3] ch.naviqore.raptor.router.RaptorRouter   : Stop ID Parent8516161 not found in lookup removing from query.
  2024-07-09T11:56:33.859+02:00  INFO 14132 --- [nio-8080-exec-3] ch.naviqore.raptor.router.Query          : Initializing global best times per stop and best labels per round
  ```
- Somehow the memory consumption seems to grow constantly while using the service. After 5-10 requests we are already at over 3 GB memory consumption in the GTFS switzerland case.
  ```txt
  http://localhost:8080/routing/connections?sourceStopId=Parent8503059&targetStopId=Parent8516161&datetime=2024-07-09T01:10:00
  ```
  image
  After some time the GC cleans up some of the memory. But I am still wondering why we are using this much memory now? It used to be around 1.2GB.
  image
- I think we should dive into the range search function and try to speed it up. It uses a lot of time in the transfer generation and also if we query from locations (see `getStopsWithWalkTimeFromLocation` in `PublicTransitServiceImpl`).
image

**Comment by clukas1** [comment]
> Maybe we should reduce the log level to debug and only output the first log statement in INFO (also better for performance):
2024-07-09T11:56:33.573+02:00  INFO 14132 --- [nio-8080-exec-3] ch.naviqore.raptor.router.RaptorRouter   : Routing earliest arrival from [Parent8503059, 8503059] to [8516161:0:2, 8516161:0:3, 8516161:0:5, 8516161:0:6, 8516161:0:7, Parent8516161, 8516161:0:1] departing at [2008-07-09T01:05, 2008-07-09T01:05]
2024-07-09T11:56:33.573+02:00  WARN 14132 --- [nio-8080-exec-3] ch.naviqore.raptor.router.RaptorRouter   : Stop ID Parent8503059 not found in lookup removing from query.
2024-07-09T11:56:33.573+02:00  WARN 14132 --- [nio-8080-exec-3] ch.naviqore.raptor.router.RaptorRouter   : Stop ID Parent8516161 not found in lookup removing from query.
2024-07-09T11:56:33.859+02:00  INFO 14132 --- [nio-8080-exec-3] ch.naviqore.raptor.router.Query          : Init

Agree, this probably doesn't hurt. No need for that much logging except when we are debugging.

> Somehow the memory consumption seems to grow constantly while using the service. After 5-10 requests we are already at over 3 GB memory consumption in the GTFS switzerland case.

I think the raptor itself has become more memory intensive after including the entire schedule instead of only the active trips for a given service day, by which factor that is, I'm not sure. But probably not the only thing. I haven't looked very deep into this. The only thing I realized was that my new implementation (NAV-126) the stop times array contains 16'000'000 int values (4 byte (32bit) per int? --> 64 MB per service day in the cache not counting the trip masks in the cache of the service. When looking at the benchmark my memory was constantly at ~3.5 GB but I didn't see any growth over time.

**Comment by clukas1** [comment]
> I think we should dive into the range search function and try to speed it up. It uses a lot of time in the transfer generation and also if we query from locations (see getStopsWithWalkTimeFromLocation in PublicTransitServiceImpl).

Yes, this has been bugging me for a while. However, I haven't found a smarter way (haven't spent much time on it) to make the range search more effective. The only thing I see we can reduce is calculating the distance between stops when we've already calculated the distance in reverse order (since we go stop by stop, we calculate each distance twice). However, I don't think calculating the distance is costing us that much time but the recursive search in the KD-Tree.

**Comment by clukas1** [comment]
Closing pull request in favor of NAV-126

**Pull request closed without merging**
