### PR TITLE
Feature/nav 53 build service implementation based on gtfs and raptor

### PR DESCRIPTION
**Pull request by munterfi**
First version of a public transit service implementation and a corresponding spring service.

PR is not yet ready, but we should start from here when refactoring the raptor package.

### CODE REVIEW

**Review by clukas1 — COMMENTED** [review]
Generally good to go.

Couple minor things to discuss and maybe change at a later stage:
- I would probably remove the KDTree inside the GTFS Schedule, as we will be building a new one inside our service.
- I'm not completely convinced of splitting Walks and Transfers. For one because I think the Walks should also include fields for stops as they will typically also include 1 stop and this data might be practical for later use cases. And therefore the only difference between Transfers and Walks will be that in case of Walks the Stop Field can be null.
- Another case I was thinking about is, what if the best solution is a pure walk. I see a possibility where the two locations are queried and the connecting to the closest stops results in more walking and or travel time than just walking from location A to B. Should we do a Pareto check after routing? If the fastest connection between two stops is the direct walk without using public transport, then only return the walk as connection? Of course routing has to be performed to assess if this is the case.
- Talking of Walks, NAV-35 is ready for review/approval and handles a ToDo marked in this pull request about having an interface for footpath routing. I would suggest that I integrate this pull request after merging into NAV-35 before triggering the review.

**Review by clukas1 — APPROVED** [review]

**Comment by munterfi** [comment]
Thanks for the review, @clukas1!

> * I would probably remove the KDTree inside the GTFS Schedule, as we will be building a new one inside our service.

Yes, this is already a separate task in JIRA.

> * I'm not completely convinced of splitting Walks and Transfers. For one because I think the Walks should also include fields for stops as they will typically also include 1 stop and this data might be practical for later use cases. And therefore the only difference between Transfers and Walks will be that in case of Walks the Stop Field can be null.
> * Another case I was thinking about is, what if the best solution is a pure walk. I see a possibility where the two locations are queried and the connecting to the closest stops results in more walking and or travel time than just walking from location A to B. Should we do a Pareto check after routing? If the fastest connection between two stops is the direct walk without using public transport, then only return the walk as connection? Of course routing has to be performed to assess if this is the case.

To address this I added another walk type `WalkType.DIRECT`, which can be used to connect two locations and the stop will be null (wrapped into an `Optional`). In the rare special case that we would have a connection between two stops that is a walk only, we can use the Transfer class to display this class. Since it actually is a transfer, but just in an unusual setup, not between two `PublicTransitLeg`s. Using the `LegVisitor`to traverse the connection legs, we now have a type safe setup, without the need of casting and no null checks (just one `Optional`, which I think we can live with).

> * Talking of Walks, NAV-35 is ready for review/approval and handles a ToDo marked in this pull request about having an interface for footpath routing. I would suggest that I integrate this pull request after merging into NAV-35 before triggering the review.

Perfect, let's discuss, where we inject the `FootPathRouter` into the service.

**Comment by munterfi** [comment]
Connection routing based on stop id works now but the resulting legs are still filled with null values since the trip id is missing.

The viewer is adjusted in https://github.com/naviqore/public-transit-viewer/pull/3 but still crashes due to the null values.

**Comment by munterfi** [comment]
> > * I would probably remove the KDTree inside the GTFS Schedule, as we will be building a new one inside our service.
> 
> Yes, this is already a separate task in JIRA.

Done https://github.com/naviqore/public-transit-service/pull/39

**Comment by clukas1** [comment]
Generally looking good. But would keep this issue open until everything works as expected. Suggest using this as a kind of dev branch for now.

**Pull request closed without merging**
